### ISSUE TITLE
Extension breaks Rename Symbol refactoring in VSCode

### ISSUE THREAD

**Issue by vaunus** [Grimones/vscode-styled-jsx-languageserver#5]
It looks like this extension is breaking the "Rename Symbol" refactoring operation (the shortcut is F2 on a Mac). 
I have disabled all other extensions and the issue is still present in VSCode Version 1.22.1.

**Comment by Grimones** [comment]
For now this is the best fix which i can do in a given period of time.

As i understood, the issues is caused by the css language server which overrides rename symbols. It works with full texted documents, [removes](https://github.com/Grimones/vscode-styled-jsx-languageserver/blob/fe74527c0215a40164ebc7909f2b0c514acbe8d3/server/src/styled-jsx-server-main.ts#L255) everything unrelated to css, and [gives](https://github.com/Grimones/vscode-styled-jsx-languageserver/blob/fe74527c0215a40164ebc7909f2b0c514acbe8d3/server/src/styled-jsx-server-main.ts#L258) it to css language server to rename symbols.

I have tried to give a full text document, with all code to the css language server, but he doesn't know how to rename anything other than the css syntax.

This is musthave feature. I will dig into this issue as i will have more spare time.
